### ISSUE TITLE
Do we need three different servers and three different domains?

### ISSUE THREAD

**Issue by gin94tjvm** [ledjon-behluli/BlazorWasmPOC#2]
Thanks for your great content.
but it's not work. 
1.
www.mydomain.com <= portal 
admin.mydomain.com  <= amdin
always show welcome to nginx.
it may show /usr/share/nginx/html/index.html in revers-proxy nginx
2.
acme-companion  | [Sun Oct 30 10:59:29 UTC 2022] Pending
acme-companion  | [Sun Oct 30 10:59:31 UTC 2022] Pending
acme-companion  | [Sun Oct 30 10:59:34 UTC 2022] Pending
3.
Can we run admin, portal, api on same port(80)? on one server(same ip)?

---
ERROR [testpoc-webapi build 4/7] RUN dotnet restore "WebApi/WebApi.csproj" 
original WebApi/Dockerfile not work. so I changed it:
`
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /App

COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "WebApi.dll"]
`

**Comment by ledjon-behluli** [comment]
Yes you can run all 3 in one server. NGINX is running within a docker container, and is exposing ports 80 and 443 which the clients can connect, afterwards NGINX will route to Portal & Admin respectively.

Note that there are prerequisites to run this:

* You need to own a domain beforehand.
* The subdomains you want to issue certificates for, must correctly resolve to the host.
* Your DNS provider must answer correctly to CAA record requests.
* Your host must be publicly reachable on both port 80 and 443.

I'd highly suggest you to read through my [article](https://www.ledjonbehluli.com/posts/blazor_wasm_nginx_docker/) on this before you being.

**Comment by gin94tjvm** [comment]
thank you for your answer.

1.
do we need this part?
```
WORKDIR "/src/Portal"
RUN dotnet build "Portal.csproj" -c Release -o /app/build
```
why? Don't you just need to publish it? we don't use /app/build at all.

2.
docker-compose down  not work. they can not find docker-compose. but can find container in docker ps -a

3.
should I serve static file (images) by kestrel or proxy nginx?

**Comment by ledjon-behluli** [comment]
1. Probably not, I took it form the the previous docs (I see they have been updated). So I guess the publish is enough.
2. I don't understand your question
3. Just place the files in the wasm projects (Admin/Portal) > wwwroot folder, where you need them. NGINX will serve them no problem. The WebApi is for endpoints only.
