### ISSUE TITLE
sitesavailable foleder does not exit.

### ISSUE THREAD

**Issue by gin94tjvm** [ledjon-behluli/BlazorWasmPOC#3]
I'm trying to find the sitesavailable folder in proxyginx, but it doesn't exist. Can't I divide vhosts into sitesavailable folders?
https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/MANUAL-CONFIGURATION.md
I'm going to apply this automatically. But some folders don't exist.

**Comment by ledjon-behluli** [comment]
Maybe this will help you: https://stackoverflow.com/questions/17413526/nginx-missing-sites-available-directory

Closing this because it is specific to nginx and has nothing to do with this repo.
